# Generated by Django 3.0.2 on 2020-01-17 17:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gml_id', models.CharField(max_length=80)),
                ('gemeinde_n', models.CharField(max_length=80)),
                ('gemeinde_s', models.CharField(max_length=80)),
                ('land_name', models.CharField(max_length=80)),
                ('land_schlu', models.CharField(max_length=80)),
                ('schluessel', models.CharField(max_length=80)),
                ('gem_s', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('animal_cou', models.CharField(max_length=254)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': ' County',
            },
        ),
        migrations.AlterModelOptions(
            name='pinlocation',
            options={'verbose_name_plural': ' PinLocation'},
        ),
    ]
